# -*- coding: utf-8 -*-
"""mult.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcxk1VVyXwjoapIx9F2aBahpt2HpuGHl
"""

def multiplicar(a, b):
    # Realiza la multiplicación
    resultado = a * b
    return resultado

# Solicita los dos números al usuario
a = float(input("Ingresa el primer número: "))
b = float(input("Ingresa el segundo número: "))

# Llama a la función y muestra el resultado
resultado = multiplicar(a, b)
print(f"El resultado de la multiplicación es: {resultado}")