# -*- coding: utf-8 -*-
"""Resta.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyON_UmPOZmAkk5RAwHRBUqCGeMMD5Fn
"""

def resta(a, b):
    return a - b