# -*- coding: utf-8 -*-
"""suma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFXHvCiPtjk8AhtvJ9PuHv2woz9zN-g-
"""

def suma(a, b):
    # Realiza la suma
    resultado = a + b
    return resultado

# Solicita los dos números al usuario
a = float(input("Ingresa el primer número: "))
b = float(input("Ingresa el segundo número: "))

# Llama a la función y muestra el resultado
resultado = suma(a, b)
print(f"El resultado de la suma es: {resultado}")